export default {
	card: {
		background: "#3bd4f5",
		effects: [
			// https://hover-tilt.simey.me/options/props/
			["shadow", "true"],
			["glare-intensity", "0.5"],
			["glare-hue", "200"],
			["scale-factor", "1.1"],
			["tilt-factor", "1"],
			["tilt-factor-y", "1"],
		],
		rank: ["ace", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
		suite: ["spades", "clubs", "hearts", "diamonds"],
	},
	sparticle: {
		abyss: {
			count: 799,
			speed: 13,
			parallax: 17.4,
			direction: 0,
			xVariance: 2.6,
			yVariance: 7.8,
			alphaSpeed: 21,
			alphaVariance: 0,
			minAlpha: -2,
			maxAlpha: 2,
			maxSize: 4,
			style: "both",
			drift: 5.9,
			spawnArea: 1,
			color: ["#ffffff", "#68e8f6", "#3bd4f5", "#017a98", "#017a98", "#017a98"],
		},
		stars: {
			count: 1000,
			speed: 0,
			direction: 0,
			xVariance: 0.2,
			yVariance: 0.2,
			rotate: false,
			rotation: 0,
			alphaSpeed: 4.2,
			alphaVariance: 6,
			minAlpha: -0.4,
			maxAlpha: 1.4,
			maxSize: 7,
			drift: 0,
			twinkle: true,
			spawnArea: 1,
			color: ["#ffccfe", "#b5eefb", "#95c5f4", "#c2b0e3", "#dff1ff", "#fff"],
			shape: ["star", "diamond"],
		},
		fire: {
			count: 125,
			speed: 50,
			parallax: 42,
			direction: 0,
			xVariance: 8,
			rotation: 3,
			alphaSpeed: 4,
			alphaVariance: 9,
			minSize: 4,
			maxSize: 16,
			style: "both",
			drift: 0,
			glow: 20,
			twinkle: true,
			spawnFromPoint: true,
			spawnArea: 10,
			staggerSpawn: 12,
			color: ["#ffffff", "#ffb366", "#f3ca7c", "#875005"],
			shape: ["star", "circle"],
		},
	},
};
